# Generated by Django 2.2.26 on 2022-03-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Media Categories',
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('publish_date', models.DateField()),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('login_status', models.BooleanField(default=False)),
                ('followed_users', models.ManyToManyField(to='rango.UserEntity')),
            ],
            options={
                'verbose_name_plural': 'User Entities',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('upload_date', models.DateField()),
                ('likes', models.IntegerField()),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserEntity')),
                ('reviewed_medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Medium')),
            ],
        ),
        migrations.AddField(
            model_name='medium',
            name='medium_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserEntity'),
        ),
        migrations.AddField(
            model_name='medium',
            name='medium_category',
            field=models.ManyToManyField(to='rango.MediaCategory'),
        ),
    ]
