# Generated by Django 2.2.26 on 2022-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20220316_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medium',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medium',
            name='medium_category',
            field=models.ManyToManyField(blank=True, to='rango.MediaCategory'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='publish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medium',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='followed_users',
            field=models.ManyToManyField(blank=True, to='rango.UserEntity'),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
