# Generated by Django 2.2.26 on 2022-03-21 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20220321_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='medium_categories',
            new_name='medium_category',
        ),
        migrations.AlterField(
            model_name='medium',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 11, 41, 26)),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 11, 41, 26)),
        ),
    ]
