# Generated by Django 2.2.26 on 2022-03-25 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20220325_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 10, 18, 2)),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 10, 18, 2)),
        ),
    ]
