# Generated by Django 2.2.26 on 2022-03-25 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0017_auto_20220325_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 16, 2, 51)),
        ),
        migrations.AlterField(
            model_name='medium',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 16, 2, 51)),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='profile_picture',
            field=models.ImageField(default='Default_profile_picture.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='Default_profile_picture.jpg', upload_to=''),
        ),
    ]
