# Generated by Django 2.2.26 on 2022-03-25 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20220325_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 19, 29, 39)),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 19, 29, 39)),
        ),
    ]
