# Generated by Django 2.2.26 on 2022-03-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0020_auto_20220326_1210'),
        ('rango', '0020_auto_20220326_2139'),
    ]

    operations = [
    ]
