# Generated by Django 2.2.26 on 2022-03-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0023_auto_20220328_1118'),
        ('rango', '0023_auto_20220328_1213'),
    ]

    operations = [
    ]
